server:
  port: 8082

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jms:
    servicebus:
      connection-string: # TODO: enter the connection string
      topic-client-id: # TODO: enter the subscription name
      pricing-tier: standard

logging:
  level:
    cz.inventi.kpj: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.security: DEBUG
